config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # new routes

  resources :islands, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  # as owner
  namespace :owner do
    resources :islands, only: [:index, :new, :create, :update, :destroy]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end

end

app/models/island.rb
class Island < ApplicationRecord
  # associations
  belongs_to :owner, class_name: "User"
  has_many :bookings

  # ActiveStorage
  has_one_attached :picture

  # Geocoder
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :capacity, presence: true
  validates :ocean, presence: true
  validates :country, presence: true
  validates :price_per_day, presence: true
  validates :location, presence: true
  validates_inclusion_of :shark, in: [true, false]
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    if params[:query].present?
      sql_query = "country ILIKE :query OR ocean ILIKE :query OR name ILIKE :query "
      @islands = Island.where(sql_query, query: "%#{params[:query]}%")
    else
      @islands = Island.geocoded.order(:name)
      # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
      @markers = @islands.geocoded.map do |island|
        {
          lat: island.latitude,
          lng: island.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { island: island }),
          image_url: helpers.asset_url("map-marker.png")
      }
      end
    end
  end

  def show
    set_island
         @booking = Booking.new
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @marker = []
    @marker[0] =
    {
        lat: @island.latitude,
        lng: @island.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { island: @island }),
        image_url: helpers.asset_url("map-marker.png")
    }
  end

  # def new
  #   @island = Island.new
  # end

  # def create
  #   @island = Island.new(island_params)
  #   if @island.save
  #     redirect_to island_path(@island)
  #   else
  #     render 'new'
  #   end
  # end

  # New booking
  # def new
  #   set_island
  #   @booking = Booking.new
  # end

  # def create
  #   @booking = Booking.new(booking_params)
  #   set_island
  #   @booking.island = @island
  #   @booking.save
  #   redirect_to bookings_path
  # end

  # def destroy
  #   @island = Island.find(params[:id])
  #   # @island = article.find(params[:id])
  #   @island.destroy

  #   # no need for app/views/restaurants/destroy.html.erb
  #   redirect_to islands_path
  # end

  private

  def island_params
    params.require(:island).permit(:name)
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :nb_travelers)
  end

  def set_island
    @island = Island.find(params[:id])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  # All my bookings
  def index

    @bookings_pending = current_user.reservations.order(:status, :start_date).where(status: "pending")
    @bookings_accepted = current_user.reservations.order(:status, :start_date).where(status: "accepted")
    @bookings_refused = current_user.reservations.order(:status, :start_date).where(status: "refused")
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to owner_bookings_path
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.update(status: "refused")
    redirect_to owner_bookings_path
  end
end

app/controllers/owner/islands_controller.rb
class Owner::IslandsController < ApplicationController
  # All my islands
  def index
    @islands = current_user.islands
    @island = Island.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.owner = current_user

    if @island.save
      redirect_to owner_islands_path(@island)
    else
      @islands = current_user.islands
      render "owner/islands/index"
    end
  end

  def update
    @island = Island.find(params[:id])
    @island.update(island_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    # no need for app/views/restaurants/create.html.erb
    redirect_to owner_islands_path
  end

  def destroy
    @islands = current_user.islands
    @island = Island.find(params[:id])
    if @island.bookings.empty?
      @island.destroy
      redirect_to owner_islands_path(@islands)
    else
      flash.alert = "You can't destroy this island is booked"
      render "owner/islands/index"
    end
    # no need for app/views/restaurants/destroy.html.erb
  end

  def island_params
    params.require(:island).permit(:country, :ocean, :location, :name, :picture, :price_per_day, :shark, :description, :picture)
  end
end

app/views/owner/islands/_new.html.erb
<%= simple_form_for [ :owner, @island ] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :ocean %>
    <%= f.input :location, :label => "Position",  input_html: { "data-tooltip" => true, :class => "has-tip", :title => "Please give " } %>
    <%= f.input :country, input_html: { class: 'select2' }%>
    <%= f.input :price_per_day %>
    <%= f.input :shark %>
    <%= f.input :picture %>
    <%= f.submit "Add Your Island", class: "btn btn-add-island" %>
   <% end %>

app/views/owner/islands/index.html.erb
<!-- My Islands -->
<!-- <div class="space" style="height:50px"></div> -->
<div class="container_home">
  <h1>My Island(s)</h1>
  <div class="back-button">
    <%= link_to "Back", root_path, class: "btn btn-ghost" %>
  </div>
  <% if @islands.empty?  %>
    You have <%= @islands.count %> Islands please create one <br>
    <%#= link_to "~ ADD ~ Your Island", new_owner_island_path, class: "btn btn-ghost" %>
    <% end %>
    <br>

  <div class="row">
    <div class="col-lg-6 col-md-6">
      <% @islands.each do | island | %>


        <%= link_to island_path(island) do %>

          <div class="card-index-island">

          <div class="card-category-icon">
            <%= link_to owner_island_path(island),
              method: :delete,
              data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>

            <%= cl_image_tag island.picture.key, class: "index-island-image" %>

<!--              <%= link_to owner_island_path(island) do %>
            <i id="pen" class="card-category-icon fa fa-pen"></i>
            <% end %>
-->


            <div class="information-index-cards">
              <div class="card-index-island-infos">
                <h2> <%= island.name %></h2>
                <p><%= island.ocean %>, <%= island.country %></p>

                <%# <i class="fas fa-bookmark"></i> %>
                <div class="price-capacity-index">
                  <h2 class="card-index-island-capacity"> <span><i class="fas fa-hotel"></i></span> <%=  island.capacity %><span> Housing</span></h2>
                  <h2 class="card-trip-pricing">$ <%= island.price_per_day.to_i.to_s(:delimited) %> <span> / Day</span> </h2>
                  <% if island.shark %>
                  <%= image_tag "layout/shark.png", class: "shark-image" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

        <% end %>


      <% end %>
    </div>
    <div class="col-lg-6 col-md-6">
      <h1>Add an Island</h1>
      <div class="row form_new_island">
        <%= render 'new' %>
      </div>
    </div>
  </div>
</div>