config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # new routes

  resources :islands, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  # as owner
  namespace :owner do
    resources :islands, only: [:index, :new, :create, :update, :destroy]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end

end

app/models/booking.rb
class Booking < ApplicationRecord

  # STATUS = %w[pending accepted refused]
  # associations
  belongs_to :renter, class_name: "User"
  belongs_to :island

  # Validations
  validates :start_date, presence: true
  validate :start_date_cannot_be_in_the_past

  validates :end_date, presence: true
  validate :end_date_cannot_be_less_than_start_date


  validates :nb_travelers, presence: true
  validates :total_price, presence: true
  # validates :status, inclusion: { in: STATUS }
  validates :status, presence: true

  def start_date_cannot_be_in_the_past
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_less_than_start_date
    if end_date < start_date
      errors.add(:end_date, "can't be after start date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings_pending = current_user.bookings.order(:status, :start_date).where(status: "pending")
    @bookings_accepted = current_user.bookings.order(:status, :start_date).where(status: "accepted")
    @bookings_refused = current_user.bookings.order(:status, :start_date).where(status: "refused")
  end

  def new
    @booking = Booking.new
    @island = Island.find(params[:island_id])
  end

   def create
    @booking = Booking.new(booking_params)
    @island = Island.find(params[:island_id])
    @booking.island = @island
    @booking.renter = current_user
    @booking.total_price = ((@booking.end_date - @booking.start_date).to_f) * @island.price_per_day
    if @booking.save
      redirect_to bookings_path
    else
      render "islands/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :nb_travelers)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  # All my bookings
  def index

    @bookings_pending = current_user.reservations.order(:status, :start_date).where(status: "pending")
    @bookings_accepted = current_user.reservations.order(:status, :start_date).where(status: "accepted")
    @bookings_refused = current_user.reservations.order(:status, :start_date).where(status: "refused")
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to owner_bookings_path
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.update(status: "refused")
    redirect_to owner_bookings_path
  end
end

app/controllers/owner/islands_controller.rb
class Owner::IslandsController < ApplicationController
  # All my islands
  def index
    @islands = current_user.islands
    @island = Island.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.owner = current_user

    if @island.save
      redirect_to owner_islands_path(@island)
    else
      @islands = current_user.islands
      render "owner/islands/index"
    end
  end

  def update
    @island = Island.find(params[:id])
    @island.update(island_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    # no need for app/views/restaurants/create.html.erb
    redirect_to owner_islands_path
  end

  def destroy
    @islands = current_user.islands
    @island = Island.find(params[:id])
    if @island.bookings.empty?
      @island.destroy
      redirect_to owner_islands_path(@islands)
    else
      flash.alert = "You can't destroy this island is booked"
      render "owner/islands/index"
    end
    # no need for app/views/restaurants/destroy.html.erb
  end

  def island_params
    params.require(:island).permit(:country, :ocean, :location, :name, :picture, :price_per_day, :shark, :description, :picture)
  end
end

app/views/owner/bookings/index.html.erb
<!-- My Reservations -->
<div class="space" style="height:50px"></div>
  <%= link_to "Back", root_path, class: "btn btn-ghost" %>
  <br>
  <div style="min-height:60vh">
  <h1 class="text-center">My Reservations</h1>
  <div class="row">
    <div class="col-6">
      <% @bookings_pending.each do |booking| %>
        <div class="card-product-owner">
          <%= cl_image_tag booking.island.picture.key %>
          <div class="card-product-infos">
              <span class="status_pending">
                <%= booking.status.capitalize %>
              </span>
            <div class="island_name">
              <%= link_to booking.island.name, island_path(booking.island) %>
            </div>
            <div class="price">
              <strong>$<%= booking.total_price.to_i.to_s(:delimited) %></strong> for <%= (booking.end_date - booking.start_date).to_i %> nights
            </div>
            <div class="dates">
              from <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong>
            </div>
            <div class="validation">
                <button class="btn-approved" type="button">
                  <%= link_to accept_owner_booking_path(booking), method: :patch do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                </button>
                <button class="btn-declined" type="button">
                  <%= link_to refuse_owner_booking_path(booking), method: :patch do %>
                    <i class="fas fa-times"></i>
                  <% end %>
                </button>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-6">
      <% @bookings_accepted.each do |booking| %>
        <div class="card-product-owner">
          <%= cl_image_tag booking.island.picture.key %>
          <div class="card-product-infos">
              <span class="status_accepted">
                <%= booking.status.capitalize %>
              </span>
            <div class="island_name">
              <%= link_to booking.island.name, island_path(booking.island) %>
            </div>
            <div class="price">
              <strong>$<%= booking.total_price.to_i.to_s(:delimited) %></strong> for <%= (booking.end_date - booking.start_date).to_i %> nights
            </div>
            <div class="dates">
              from <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong>
            </div>
          </div>
        </div>
      <% end %>

      <% @bookings_refused.each do |booking| %>
        <div class="card-product-owner">
          <%= cl_image_tag booking.island.picture.key %>
          <div class="card-product-infos">
              <span class="status_refused">
                <%= booking.status.capitalize %>
              </span>
            <div class="island_name">
              <%= link_to booking.island.name, island_path(booking.island) %>
            </div>
            <div class="price">
              <strong>$<%= booking.total_price.to_i.to_s(:delimited) %></strong> for <%= (booking.end_date - booking.start_date).to_i %> nights
            </div>
            <div class="dates">
              from <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>