config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # new routes

  resources :islands, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  # as owner
  namespace :owner do
    resources :islands, only: [:index, :new, :create, :update, :destroy]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © Island Paradise, inc. 2020
  </div>
</div> -->


<footer class="footer-distributed">

      <div class="footer-left">

        <h3>Island<span>Paradise</span></h3>

        <p class="footer-links">
          <a href="#" class="link-1">Home</a>

          <a href="#">Blog</a>
          <a href="#">Pricing</a>
          <a href="#">About</a>
          <a href="#">Faq</a>
          <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">IslandParadise © 2020</p>
      </div>

      <div class="footer-center">

        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>La Cantine</span>  Nantes, France</p>
        </div>

        <div>
          <i class="fa fa-phone"></i>
          <p>+33 06.12.35.64.09</p>
        </div>

        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:support@islandparadise.com">support@islandparadise.com</a></p>
        </div>

      </div>

      <div class="footer-right">

        <p class="footer-company-about">
          <span>About the company</span>
          Island Paradise has been created in a small garage in Nantes by four passionnate LeWagon Alumni who wanted to travel and discover all the islands, all around the world
        </p>

        <div class="footer-icons">

        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>

        </div>

      </div>

    </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="navbar-logo">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
    <%= image_tag "layout/logo.png" %>
    <h2>Island Paradise</h2>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">

        <!-- Enveloppe Notification  -->
        <%= link_to(owner_bookings_path, class: "nav-link notification") do %>
          <i class="fas fa-envelope-open-text"></i>&nbsp;

          <% if current_user.islands.count > 0 && current_user.reservations.where(status: "pending").count > 0 %>
            <span class="badge"><%= current_user.reservations.where(status: "pending").count %></span>
          <% end %>
        <% end %>
        </li>
        <li class="nav-item dropdown">
        <!-- Avatar  -->
        <% if current_user.avatar.present?  %>
          <%= cl_image_tag(current_user.avatar.key, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false )%>
        <% else %>
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <!-- DropDown Menu  -->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "My Islands", owner_islands_path, class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My reservations", owner_bookings_path, class: "dropdown-item" %>
            <%= link_to "Favorites", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
        <!-- Login Button  -->
        <%= link_to(new_user_session_path, class: "nav-link") do %>
          Login <i class="fas fa-globe-americas"></i>
        <% end %>

        </li>
      <% end %>
    </ul>
  </div>
</div>