config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # new routes

  resources :islands, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  # as owner
  namespace :owner do
    resources :islands, only: [:index, :new, :create, :update, :destroy]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end

end

app/views/pages/home.html.erb
 <div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://source.unsplash.com/featured/?island,paradise');)">

   <div class="container_home">
     <h1 class="home-title">Gorgeous Islands to rent </h1>
         <h2>You want to find Wilson ? come and rent an Island !</h2> <br>
         <%= link_to "~ BROWSE ~ Our Rental Islands", islands_path, class: "btn btn-flat" %>
         <%#= link_to "~ ADD ~ Your Island", owner_islands_path, class: "btn btn-flat" %>
         <%#= link_to "~ SEE ~ My Bookings", owner_bookings_path, class: "btn btn-flat" %>
         <%#= link_to "~ SEE ~ My Islands", owner_islands_path, class: "btn btn-flat" %>
        </div>
</div>

<div class="container_home">
  <div class="row">
    <div class="col-lg-12 col-sm-offset-4">
      <div class="home-title">
        Top Islands
      </div>
      <div class="cards">
        <div class="card-category shadow m-2" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.2)),url('<%= image_path("islands/narval.jpg")%>');">
          <p>Narval</p>
        </div>
        <div class="card-category shadow m-2" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.3)),url('<%= image_path("islands/whitsunday.jpg")%>');">
          <p>Whitsundays</p>
        </div>
        <div class="card-category shadow m-2" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.3)),url('<%= image_path("islands/heart.jpg")%>');">
          <p>Heart</p>
        </div>
      </div>
    </div>
  </div>
</div>